# fly.toml app configuration file generated for tictactoe-thing on 2023-10-11T20:34:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tictactoe-thing"
primary_region = "phx"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "tictactoe-thing.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
